# Phase 2A: lpuart1 DMA RX -> frame parser -> PCM ring -> SAI2 DMA -> PCM5102
CONFIG_GPIO=y
CONFIG_DISPLAY=y
CONFIG_SERIAL=y
CONFIG_UART_ASYNC_API=y
CONFIG_DMA=y
CONFIG_I2S=y
CONFIG_RING_BUFFER=y
CONFIG_HEAP_MEM_POOL_SIZE=16384
CONFIG_MAIN_STACK_SIZE=4096
CONFIG_RING_BUFFER_LARGE=y
